
module Render = struct
  (* ... *)
  
  (*
  let def d = decl_def d ^ "\n" ^ def_def d
  let program defs = List.map def defs |> String.concat "\n\n"   
  *)
end

let string_of_program spec =
  String.concat "\n" [
    "/*";
    "This is LBNF code generated by the Agda backend generator";
    "*/";
    Render.specification spec;
    "";
  ]
