-- Test for Agda binding of parser.  Requires Agda >= 2.5.4.
-- Generated by BNFC.

module SpecTec.Example.Main where
open import SpecTec.Example.IOLib
open import SpecTec.Example.AST using (printExp)
open import SpecTec.Example.Parser using (Err; parseExp)

main : IO ⊤
main = do
  file ∷ [] ← getArgs where
    _ → do
      putStrLn "usage: Main <SourceFile>"
      exitFailure
  Err.ok result ← parseExp <$> readFiniteFile file where
    Err.bad msg → do
      putStrLn "PARSE FAILED\n"
      putStrLn (stringFromList msg)
      exitFailure
  putStrLn "PARSE SUCCESSFUL\n"
  putStrLn (printExp result)
