-- File generated by the BNF Converter (bnfc 2.9.5).

-- Test for Agda binding of parser.  Requires Agda >= 2.5.4.

module Example.Main where
open import Example.IOLib
open import Example.AST using (printFloat)
open import Example.Parser using (Err; parseFloat)

main : IO ⊤
main = do
  file ∷ [] ← getArgs where
    _ → do
      putStrLn "usage: Main <SourceFile>"
      exitFailure
  Err.ok result ← parseFloat <$> readFiniteFile file where
    Err.bad msg → do
      putStrLn "PARSE FAILED\n"
      putStrLn (stringFromList msg)
      exitFailure
  putStrLn "PARSE SUCCESSFUL\n"
  putStrLn (printFloat result)
